version: 2

models:
  - name: dim_listing_cleansed
    description: The dim_listing_cleansed model provides a refined and structured view of Airbnb listings, ensuring data accuracy and usability for business analysis. It includes essential details such as listing ID, host ID, room type, and minimum nights required for booking. This model is designed to support decision-making processes, such as pricing strategies, host performance evaluation, and market trend analysis, by offering clean and reliable data.
    columns:
      - name: listing_id
        description: The unique identifier/primary key for each listing.
        data_tests:
          - unique
          - not_null
        data_type: number

      - name: host_id
        description: The unique identifier for each host.
        data_tests:
          - not_null
          - relationships:
              field: host_id
              to: ref('dim_hosts_cleansed')
        data_type: number

      - name: room_type
        data_tests:
          - accepted_values:
              values:
                - Entire home/apt
                - Private room
                - Shared room
                - Hotel room
        description: Indicates the type of room available for the listing, such as entire home/apt, private room, shared room, etc.
        data_type: varchar

      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        data_tests:
          - positive_values
        data_type: number
      - name: listing_name
        description: The name of the listing, typically provided by the host to describe the property.
        data_type: varchar
      - name: price
        data_type: number
      - name: created_at
        data_type: timestamp_ntz
      - name: updated_at
        data_type: timestamp_ntz

  - name: dim_hosts_cleansed
    config:
      contract:
        enforced: true
    columns:
      - name: host_id
        description: The unique identifier/primary key for each host.
        data_type: integer
      - name: host_name
        description: The name of the host.
        data_type: string
      - name: is_superhost
        description: Indicates if the host is a superhost.
        data_type: string
      - name: updated_at
        description: The timestamp when the host information was last updated.
        data_type: timestamp
      - name: created_at
        description: The timestamp when the host record was created.
        data_type: timestamp
  - name: test_model
    description: The test_model aggregates and transforms raw review data from the AIRBNB.raw.raw_reviews source. It extracts key fields such as listing_id, review_date, reviewer_name, review_text, and review_sentiment to provide a structured view of review information for further analysis.
