models:
  - name: dim_listing_cleansed
    description: Cleansed table which contains Airbnb listings.
    columns:
      - name: listing_id
        description: The unique identifier/primary key for each listing.
        data_tests:
          - unique
          - not_null

      - name: host_id
        description: The unique identifier for each host.
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_hosts_cleansed')
                field: host_id

      - name: room_type
        data_tests:
          - accepted_values:
              arguments:
                values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']

      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        data_tests:
          - positive_values

  - name: dim_hosts_cleansed
    config:
        contract:
          enforced: true
    columns:
      - name: host_id
        description: The unique identifier/primary key for each host.
        data_type: integer
      - name: host_name
        description: The name of the host.
        data_type: string
      - name: is_superhost
        description: Indicates if the host is a superhost.
        data_type: string
      - name: updated_at
        description: The timestamp when the host information was last updated.
        data_type: timestamp
      - name: created_at
        description: The timestamp when the host record was created.
        data_type: timestamp